### ISSUE TITLE
Max heap size for local mode should not be set to 1GB

### ISSUE THREAD

**Issue by jerome73** [Hurence/logisland#391]
# Expected behavior and actual behavior.
When running a logisland job in local mode, it is failing with an NPE (due to an OOM exception) while it is passing when running in yarn-client or yarn-cluster.

Here is what we see of the job launched in local mode:
```
29874 org.apache.spark.deploy.SparkSubmit --class com.hurence.logisland.runner.StreamProcessingRunner --jars /opt/Logisland/logisland-0.13.0/lib/zookeeper-3.4.6.jar,/opt/Logisland/logisland-0.13.0/lib/zkclient-0.8.jar,/opt/Logisland/logisland-0.13.0/lib/yauaa-1.2.jar,/opt/Logisland/logisland-0.13.0/lib/xz-1.0.jar,/opt/Logisland/logisland-0.13.0/lib/xmlbeans-2.6.0.jar,/opt/Logisland/logisland-0.13.0/lib/woodstox-core-asl-4.4.1.jar,/opt/Logisland/logisland-0.13.0/lib/unused-1.0.0.jar,/opt/Logisland/logisland-0.13.0/lib/stax-api-1.0.1.jar,/opt/Logisland/logisland-0.13.0/lib/stax2-api-3.1.4.jar,/opt/Logisland/logisland-0.13.0/lib/spring-core-4.3.2.RELEASE.jar,/opt/Logisland/logisland-0.13.0/lib/spatial4j-0.6.jar,/opt/Logisland/logisland-0.13.0/lib/spark-streaming-kafka-assembly_2.10-1.6.2.jar,/opt/Logisland/logisland-0.13.0/lib/spark-metrics_spark-1.x-2.0.0.jar,/opt/Logisland/logisland-0.13.0/lib/solr-solrj-6.4.2.jar,/opt/Logisland/logisland-0.13.0/lib/snappy-java-1.0.5.jar,/opt/Logisland/logisland-0.13.0/lib/snakeyaml -Dhdp.version=2.4.3.0-227 -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=0.0.0.0:7777 -Xms1g -Xmx1g
```
Note that in the logisland job config, we set the driver and the executor memory params such as:
```
# engine
engine:
  component: com.hurence.logisland.engine.spark.KafkaStreamProcessingEngine
  type: engine
  documentation: Index web events to ES
  configuration:
    spark.app.name: IndexWebEventsToES
    spark.master: local[4]
    spark.driver.memory: 2G
    spark.driver.cores: 1
    spark.monitoring.driver.port: 7092
    spark.executor.memory: 4G
    spark.executor.instances: 4
....
```
When running a logisland job in local mode, the java heap size should not be set to 1GB.
Indeed when using the user agent processor, then it is already consuming about 700MB; that is expected.
Then if we also need to perform some ip2geo lookup, then the ip2geo processor will try to load the geolite db into memory but fails with an OOM exception.

When running logisland in local mode, it is expected to be able to set the heap size to a desired size; 
An option could be to use the memory parameter for the driver.

# Steps to reproduce the problem.
Define a logisland job with 2 processors (useragent and ip2geo)
Configure it to be launched wth local mode.

# Specifications like the version of the project, operating system, or hardware.
Version: 0.13.0 (maybe the pb also happen with earlier release, haven't tested it)
OS: any
HW: any
