### ISSUE TITLE
Allow yaml object in component configurations

### ISSUE THREAD

**Issue by MiniPlayer** [Hurence/logisland#494]
Currently the configuration of a components is a map of key value pair as Strings.

It would be convenient to be able to specify yaml collection, map and object so that we can initialize them directly with a method like "asList<MyBean>" which would return a list of MyBean. Of course the developer would have to implement a validator that verify the configuration accordingly.

This feature would simplify complexe configuration, at the moment we often need dynamic properties which is not easy to read or use.

For exemple, in the case of the AddFields processor instead of : 
```
config:
  new_field: aromate
  new_field.type: STRING
  new_field_2: 12
  new_field_2.type: INT
```
We would have : 
```
config:
  - name: new_field
    value: aromate
    type: STRING
  - name: new_field_2
    value: 12
    type: INT
```
