### ISSUE TITLE
Strip URL query parameters processeur

### ISSUE THREAD

**Issue by MiniPlayer** [Hurence/logisland#567]
# Description

The field containing the URL value of the visited website MAY contain a set of query parameters.
The following query parameters are undesired (btw the list might evolve):
- _ga
- ga
- page
- v
- s
- r
- autoStart

The presence of the query parameters prevent from processing efficiently the URL in client application.
For instance they introduce noise while doing segmentation per visited page. Indeed the same visited page may be considered as 2 different pages for instance. 

# Needs

Therefore it is asked to be able to build a new field out of a URL value, cleaned from a customizable set of undesired query parameters. 

* first design the conf of the processor to add
* then implement the processor
* then add unit test

**Comment by MiniPlayer** [comment]
The name of the processor will be URLCleaner to be like URLDecoder.
I suggest two solutions :

conf1 :  
```yaml
url.fields : [comma separated list]            required
param.names : [comma separated list]   required
new.url.fields : [comma separated list]    par defaut la même chose que "url.fields"
conflict.resolution.policy : [overwrite_existing|keep_only_old_field]            required      default to overwrite_existing
remove.all.params: [bolean]                    required       default to false
```
ou alors une conf avec des propriétés dynamiques pour avoir plus de control individuelle :

```yaml
myurl : <url>   le nom de l'url
myurl.param.names : [comma separated list]            required
myurl.new.field : [String]          champ ou mettre la nouvelle valeur 
myurl.conflict.resolution.policy : [overwrite_existing|keep_only_old_field] 
myurl.remove.all.params :[bolean]                    required       default to false
```
Bref la même chose avec des propriétés dynamiques afin de pouvoir spécifier des paramètres différents pour différent urls. 

Je recommande la solution 1 qui est plus simple et suffisante.
